# SPDX-FileCopyrightText: 2025 Eric Joldasov
#
# SPDX-License-Identifier: 0BSD

[versions]
kotlin = "2.2.20"
dokka = "2.1.0-Beta"
shadow = "9.1.0"

spigot = "1.12.2-R0.1-SNAPSHOT"
password4j = "1.8.4"
sqldelight = "2.1.0"

[libraries]
spigot-api = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
password4j = { group = "com.password4j", name = "password4j", version.ref = "password4j" }
sqldelight-sqlite = { group = "app.cash.sqldelight", name = "sqlite-driver", version.ref = "sqldelight" }
# SpigotMC 1.12.2 includes SQLite version 3.21
sqldelight-sqlite-dialect = { group = "app.cash.sqldelight", name = "sqlite-3-18-dialect", version.ref = "sqldelight" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }